In [1]:
import pandas as pd
import numpy as np
import random
import os
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'NanumGothic' # 폰트 변경
plt.rcParams['axes.unicode_minus'] = False # 축 값 마이너스 깨짐 해결
from collections import defaultdict
from scipy import stats as stats
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import KFold
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42) # Seed 고정

In [3]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [4]:
test_cols = [
    # '나이', 
    '키(cm)', 
    '몸무게(kg)', 
    # 'BMI', 
    '시력', 
    # '충치', 
    # '공복 혈당', 
    '혈압',
    # '중성 지방', 
    # '혈청 크레아티닌', 
    '콜레스테롤', 
    '고밀도지단백', 
    '저밀도지단백', 
    '헤모글로빈', 
    '요 단백',
    # '간 효소율'
]
train_cols = test_cols + ['label']

In [6]:
train = train[train_cols]
x_test = test[test_cols]

In [10]:
from pycaret.classification import *

x_train = setup(data=train,
                target='label',
                train_size=0.8,
                fold=5)

In [14]:
best = compare_models(sort='Accuracy')

In [15]:
best_tune = tune_model(best)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

In [16]:
evaluate_model(best_tune)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [17]:
predict_model(best_tune)

,키(cm),몸무게(kg),시력,혈압,콜레스테롤,고밀도지단백,저밀도지단백,헤모글로빈,요 단백,label,prediction_label,prediction_score
189,165,70,1.20,57,206,61,106,16.6,1,0,1,0.6927
3141,160,70,0.95,52,200,54,128,15.8,1,0,0,0.5830
6776,175,75,1.20,40,175,48,119,17.0,1,1,0,0.5136
2103,170,70,0.35,56,251,58,159,13.7,1,1,0,0.6383
3583,150,55,1.00,52,186,63,112,12.1,1,0,0,0.9777
...,...,...,...,...,...,...,...,...,...,...,...,...
2235,170,65,1.35,49,172,67,96,14.4,1,0,1,0.5216
4291,160,50,1.00,50,131,50,59,15.0,1,0,0,0.5585
1397,170,70,1.10,40,125,51,63,14.0,1,1,0,0.5236
5001,175,80,0.75,59,203,47,124,14.9,1,1,0,0.5177
5851,175,70,1.50,40,213,63,125,16.0,1,1,1,0.5099

In [18]:
predict_model(best_tune, data= x_test)

,키(cm),몸무게(kg),시력,혈압,콜레스테롤,고밀도지단백,저밀도지단백,헤모글로빈,요 단백,prediction_label,prediction_score
0,165,55,0.90,47,229,59,155,13.700000,1,0,0.8379
1,145,50,0.50,59,200,65,115,12.200000,1,0,0.9793
2,160,75,1.00,34,170,50,73,15.100000,1,1,0.5021
3,180,90,1.35,45,197,55,98,15.200000,1,1,0.6860
4,155,55,0.75,67,230,66,136,15.000000,1,0,0.9092
...,...,...,...,...,...,...,...,...,...,...,...
2995,170,90,0.85,60,221,55,137,14.300000,1,1,0.5341
2996,175,80,1.00,50,167,47,100,13.900000,1,0,0.5391
2997,155,60,1.20,32,186,61,114,12.800000,1,0,0.9738
2998,175,90,1.35,42,163,44,91,16.299999,1,0,0.5541
2999,150,60,0.80,32,189,61,106,12.400000,1,0,0.9729